/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AlgoUpdateAo
 */
export interface AlgoUpdateAo {
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    caid?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof AlgoUpdateAo
     */
    aid?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    at?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    o?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    s?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    S?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    ps?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    f?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    q?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    X?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    ai?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    ap?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    aq?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    act?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    tp?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    p?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    V?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    wt?: string;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    pm?: string;
    /**
     *
     * @type {boolean}
     * @memberof AlgoUpdateAo
     */
    cp?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof AlgoUpdateAo
     */
    pP?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof AlgoUpdateAo
     */
    R?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof AlgoUpdateAo
     */
    tt?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof AlgoUpdateAo
     */
    gtd?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof AlgoUpdateAo
     */
    rm?: string;
}
